In [44]:
import numpy as np

data1= [6, 7.5, 8, 0, 1]
arr1= np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [45]:
data2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)
data2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [46]:
dim1=arr1.ndim
dim1

1

In [47]:
shape1=arr1.shape
shape1

(5,)

In [48]:
dim2=arr2.ndim
dim2

2

In [49]:
shape2=arr2.shape
shape2

(2, 4)

In [50]:
print(arr1.dtype)

float64


In [51]:
print(arr2.dtype)

int32


In [52]:
np.zeros(4) # 1D

array([0., 0., 0., 0.])

In [53]:
np.zeros((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [54]:
np.zeros((2,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [55]:
np.empty((2,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [56]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [57]:
np.ones((2,4,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [58]:
np.zeros_like(arr2)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [59]:
np.ones_like(arr2)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])