In [12]:
import numpy as np
arr1=np.array([1,2,3], dtype=np.float64)
arr1

array([1., 2., 3.])

In [13]:
arr1.dtype

dtype('float64')

In [14]:
np.zeros((4,2)).dtype

dtype('float64')

In [15]:
np.zeros((4,2), dtype=np.int64).dtype

dtype('int64')

In [16]:
# Casting
arr3=arr1.astype(np.float64)
arr3.dtype

dtype('float64')

In [17]:
arrint=np.array([3.2, -1.2, -2.6, 0.5, 12.9, 10.1])
arrint

array([ 3.2, -1.2, -2.6,  0.5, 12.9, 10.1])

In [18]:
arrint.astype(np.int64)

array([ 3, -1, -2,  0, 12, 10], dtype=int64)

In [19]:
arr_string=np.array(['1.2', '3.4', '5.6'])
print(arr_string.dtype)
arr_string.astype(np.float64)

<U3


array([1.2, 3.4, 5.6])

Calling ``astype()`` always create a new array(a copy of data), even if the new dtype is the same as the old dtype