Arrays are important in Numpy because they enable you to express batch operations on data without having to write any ``for`` loops. Numpy users call this **Vectorization**. **Any arithmetic operations between equal-size arrays applies the operation element-wise**

In [11]:
import numpy as np

arr=np.array([[1.,2.,3.],[4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [12]:
arr+arr

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [13]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [14]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [15]:
arr*0.5

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [16]:
arr**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [17]:
# Comparison between equal size arrays
arr2=np.array([[0., 4., 1.],[7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [18]:
arr<arr2

array([[False,  True, False],
       [ True, False,  True]])

Operations between different-sized array is called broadcasting and will be disucssed later