In [45]:
import numpy as np
arr=np.arange(15)
arr[5]

5

In [46]:
arr[5:8]

array([5, 6, 7])

In [47]:
arr[5:8]=0
arr

array([ 0,  1,  2,  3,  4,  0,  0,  0,  8,  9, 10, 11, 12, 13, 14])

In [48]:
arr_slice=arr[5:8]
arr_slice[0]=9999999
arr_slice

array([9999999,       0,       0])

In [49]:
arr

array([      0,       1,       2,       3,       4, 9999999,       0,
             0,       8,       9,      10,      11,      12,      13,
            14])

In [50]:
arr_slice[:]=888
arr

array([  0,   1,   2,   3,   4, 888, 888, 888,   8,   9,  10,  11,  12,
        13,  14])

As seen above, signing a scalar number to a slice of array enables the value to be propagated to the entire selection and the numpy array is mmutable

In [51]:
# Slicing from multi-dimentional array
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[2]

array([7, 8, 9])

In [52]:
arr2d[0][1]

2

In [53]:
arr2d[0,1] # pass a comma-seperated list of indices to select individual elements. It does the 
# the same job as the code above

2

In [54]:
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [55]:
arr3d.shape

(2, 2, 3)

In [56]:
# get a two dimentional array with the sam evalues
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
arr3d[0][0]

array([1, 2, 3])

In [58]:
arr3d[0][0][0]

1

In [59]:
arr3d[0,0,0]

1

In [60]:
old_values=arr3d[0].copy()
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
arr3d[0]=888
arr3d

array([[[888, 888, 888],
        [888, 888, 888]],

       [[  7,   8,   9],
        [ 10,  11,  12]]])

In [62]:
arr3d[0]=old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [63]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
# Slicing two dimentional arrays
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
# Pass multiple slice like you can pass multiple indexces
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [66]:
arr2d[1, :2]

arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
arr2d[:2, 2]

array([3, 6])

In [68]:
arr2d[:, :]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [70]:
arr2d[:1, :]

array([[1, 2, 3]])

In [71]:
arr2d[:2, 1:]=0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [72]:
a1=arr2d[2]
print(a1.shape)
a1



(3,)


array([7, 8, 9])

In [73]:
a2=arr2d[2, :]
print(a2.shape)
a2

(3,)


array([7, 8, 9])

In [74]:
a3=arr2d[2:, :]
print(a3.shape)
a3

(1, 3)


array([[7, 8, 9]])

In [75]:
a4=arr2d[1, :2]
print(a4.shape)
a4

(2,)


array([4, 0])

In [76]:
a5=arr2d[1:2, :2]
print(a5.shape)
a5

(1, 2)


array([[4, 0]])