In [26]:
import numpy as np

names= np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [27]:
data=np.random.randn(7,4)
data

array([[ 1.31174119, -1.90377182, -0.5509565 , -1.21709021],
       [ 1.40697747,  0.10944824,  0.27864003,  0.56909743],
       [ 0.31938121,  0.63669644,  0.60790982, -0.29961088],
       [ 1.08294464,  0.80382305, -0.07002043,  0.43926694],
       [-0.25502022, -0.14111162, -0.85975088, -0.46905343],
       [ 1.04276638, -0.70095718, -2.14540332,  0.2743693 ],
       [ 0.05464611, -1.17810245,  0.96260817,  1.11419625]])

Suppose each name corresponds to a row in the data array and we want to find out all the rows with corresponding name 'Bob'


In [28]:
names =='Bob'# vectorization

array([ True, False, False,  True, False, False, False])

In [29]:
data[names=='Bob']

array([[ 1.31174119, -1.90377182, -0.5509565 , -1.21709021],
       [ 1.08294464,  0.80382305, -0.07002043,  0.43926694]])

The boolean array must be of the same length as the array axis it's indexing

In [30]:
data[names=='Bob', :]

array([[ 1.31174119, -1.90377182, -0.5509565 , -1.21709021],
       [ 1.08294464,  0.80382305, -0.07002043,  0.43926694]])

In [31]:
data[names=='Bob', 1:]

array([[-1.90377182, -0.5509565 , -1.21709021],
       [ 0.80382305, -0.07002043,  0.43926694]])

In [32]:
data[names=='Bob', 3]

array([-1.21709021,  0.43926694])

In [33]:
# Select anything that is not Bob
data[names !='Bob']

array([[ 1.40697747,  0.10944824,  0.27864003,  0.56909743],
       [ 0.31938121,  0.63669644,  0.60790982, -0.29961088],
       [-0.25502022, -0.14111162, -0.85975088, -0.46905343],
       [ 1.04276638, -0.70095718, -2.14540332,  0.2743693 ],
       [ 0.05464611, -1.17810245,  0.96260817,  1.11419625]])

In [34]:
data[~(names =='Bob')] # neglect

array([[ 1.40697747,  0.10944824,  0.27864003,  0.56909743],
       [ 0.31938121,  0.63669644,  0.60790982, -0.29961088],
       [-0.25502022, -0.14111162, -0.85975088, -0.46905343],
       [ 1.04276638, -0.70095718, -2.14540332,  0.2743693 ],
       [ 0.05464611, -1.17810245,  0.96260817,  1.11419625]])

The **~** operator can be useful when you want to invert a general condition

In [35]:
condition=names=='Bob'
data[~condition]



array([[ 1.40697747,  0.10944824,  0.27864003,  0.56909743],
       [ 0.31938121,  0.63669644,  0.60790982, -0.29961088],
       [-0.25502022, -0.14111162, -0.85975088, -0.46905343],
       [ 1.04276638, -0.70095718, -2.14540332,  0.2743693 ],
       [ 0.05464611, -1.17810245,  0.96260817,  1.11419625]])

In [36]:
condition2=(names=='Bob') | (names=='Will')
condition2

array([ True, False,  True,  True,  True, False, False])

In [37]:
data[condition2]

array([[ 1.31174119, -1.90377182, -0.5509565 , -1.21709021],
       [ 0.31938121,  0.63669644,  0.60790982, -0.29961088],
       [ 1.08294464,  0.80382305, -0.07002043,  0.43926694],
       [-0.25502022, -0.14111162, -0.85975088, -0.46905343]])

In [38]:
data[~condition2]

array([[ 1.40697747,  0.10944824,  0.27864003,  0.56909743],
       [ 1.04276638, -0.70095718, -2.14540332,  0.2743693 ],
       [ 0.05464611, -1.17810245,  0.96260817,  1.11419625]])

In [39]:
data[data<0]=0
data

array([[1.31174119, 0.        , 0.        , 0.        ],
       [1.40697747, 0.10944824, 0.27864003, 0.56909743],
       [0.31938121, 0.63669644, 0.60790982, 0.        ],
       [1.08294464, 0.80382305, 0.        , 0.43926694],
       [0.        , 0.        , 0.        , 0.        ],
       [1.04276638, 0.        , 0.        , 0.2743693 ],
       [0.05464611, 0.        , 0.96260817, 1.11419625]])

In [41]:
data[names !='Joe']=7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [1.40697747, 0.10944824, 0.27864003, 0.56909743],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [1.04276638, 0.        , 0.        , 0.2743693 ],
       [0.05464611, 0.        , 0.96260817, 1.11419625]])