A universal function or *ufunc* is a function that performs element-wise operations on data in ndarrays. 
you can think of them as fast vectorized wrappers for simple functions that make one or more scalar values and produce one or more scalar results.


In [35]:
import numpy as np
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [37]:
np.square(arr)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [38]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

Above are unary ufuncs and others, such as *add* or *maximum*, take two arrays (thus, *binary ufuncs*) and return a single array as the result:

In [39]:
x=np.random.randn(8)
x


array([-2.30841123, -0.46799398,  2.05354118, -0.02583727, -1.50620423,
       -0.76416145, -1.15125108,  0.58322062])

In [40]:
y=np.random.randn(8)
y


array([-2.24848685,  0.65805103,  0.58213572,  0.74077327, -0.83293713,
        0.85001309, -0.60784922,  1.21629113])

In [41]:
np.maximum(x,y)

array([-2.24848685,  0.65805103,  2.05354118,  0.74077327, -0.83293713,
        0.85001309, -0.60784922,  1.21629113])

***modf***, a vectorized version of the built-in python *divmod*. It returns the fractional and integer parts of the floating-point array. This is one example that a ufunc can return multiple arrays.

In [42]:
arr=np.random.randn(7)*5
arr

array([-0.69741462,  4.30517048,  5.60730715, -4.58555022,  3.62567875,
       -2.95392488,  3.17124443])

In [43]:
reminder, whole_part=np.modf(arr)


In [44]:
reminder

array([-0.69741462,  0.30517048,  0.60730715, -0.58555022,  0.62567875,
       -0.95392488,  0.17124443])

In [45]:
whole_part

array([-0.,  4.,  5., -4.,  3., -2.,  3.])

**Ufuncs accept an optional out argument that allows them to operate in-place on arrays.**

In [46]:
arr=np.random.randn(8)
arr

array([ 1.9608901 ,  1.01401423, -0.43672958,  0.38285696,  0.27811244,
        0.94570768, -0.22373077, -1.11686511])

In [47]:
np.sqrt(arr)

C:\Users\fanda\AppData\Local\Temp\ipykernel_15680\2296558006.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([1.40031786, 1.00698274,        nan, 0.61875437, 0.52736367,
       0.97247503,        nan,        nan])

In [48]:
arr

array([ 1.9608901 ,  1.01401423, -0.43672958,  0.38285696,  0.27811244,
        0.94570768, -0.22373077, -1.11686511])

In [49]:
np.sqrt(arr, arr)

C:\Users\fanda\AppData\Local\Temp\ipykernel_15680\269955669.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr, arr)


array([1.40031786, 1.00698274,        nan, 0.61875437, 0.52736367,
       0.97247503,        nan,        nan])

In [50]:
arr

array([1.40031786, 1.00698274,        nan, 0.61875437, 0.52736367,
       0.97247503,        nan,        nan])