Aggregate statistics

In [56]:
import numpy as np
arr=np.random.randn(5,4)
arr


array([[-1.81209438,  0.53790711,  0.27964936,  0.25307601],
       [ 0.01724595,  1.4097098 , -0.34254915,  1.03453027],
       [-0.02723392, -0.45879086, -0.68021159, -0.46445967],
       [ 0.36977123,  0.41646069,  0.58285665,  0.91356733],
       [-1.07549462,  0.48072817,  0.88019871, -0.95071859]])

In [57]:
np.mean(arr)

0.06820742594034271

In [58]:
np.mean(arr)

0.06820742594034271

In [59]:
np.sum(arr)

1.364148518806854

Functions like mean and sum take an optional ***axis*** argument that computes the statistics over the given axis, resulting in an array with one fewer dimensions.
- axis=0: compute down the rows. the number of columns doesn't change
- aixis=1: compute across the columns. the number of rows doesn't change

In [60]:
arr=np.arange(6).reshape(3,2)
arr

array([[0, 1],
       [2, 3],
       [4, 5]])

In [61]:
np.mean(arr, axis=0) 

array([2., 3.])

In [62]:
np.sum(arr, axis=0)

array([6, 9])

In [63]:
np.sum(arr, axis=1)

array([1, 5, 9])

In [64]:
np.mean(arr, axis=1)

array([0.5, 2.5, 4.5])

Cumulated sum

In [65]:
arr=np.array([0,1,2,3,4,5,6,7])
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [66]:
np.cumsum(arr)

array([ 0,  1,  3,  6, 10, 15, 21, 28])

In [67]:
arr=np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [68]:
np.cumsum(arr, axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [69]:
np.cumsum(arr, axis=1)

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]])

In [70]:
np.cumprod(arr, axis=0)

array([[ 0,  1,  2],
       [ 0,  4, 10],
       [ 0, 28, 80]])

In [71]:
np.cumprod(arr, axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]])

In [72]:
np.std(arr)

2.581988897471611

In [73]:
np.std(arr, axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [74]:
np.std(arr, axis=1)

array([0.81649658, 0.81649658, 0.81649658])

In [75]:
np.var(arr)

6.666666666666667

In [76]:
np.var(arr, axis=0)

array([6., 6., 6.])

In [77]:
np.var(arr, axis=1)

array([0.66666667, 0.66666667, 0.66666667])