NumPy has some basic set opertions or 1-dimentional ndarrays. A commonly used one is ***np.unique*** which returns the sorted unique values in an array.

In [16]:
import numpy as np
names=np.array(['Bob', 'Will', 'Joe', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)


array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [17]:
ints=np.array([3,3,3,2,2,2,1,1,7,3,7,9])

In [18]:
np.unique(ints)

array([1, 2, 3, 7, 9])

Function ***np.in1d*** computes a boolean array indicating whether element of x is containted in y

In [19]:
values=np.array([6,0,0,0,2,3,4])
np.in1d(values,[2,3,5])

array([False, False, False, False,  True,  True, False])

Computer the sorted, common elements in x and y: ***intersectid(x,y)***

In [20]:
values2=np.array([6,0,0,8,2,9,5,10,11,4])
np.intersect1d(values,values2)

array([0, 2, 4, 6])

Compute the sorted, union of elements ***union1d***

In [21]:
np.union1d(values,values2)

array([ 0,  2,  3,  4,  5,  6,  8,  9, 10, 11])

Set difference, elements in x that are not in y

In [23]:
np.setdiff1d(values,values2)

array([3])

In [24]:
np.setdiff1d(values2,values)

array([ 5,  8,  9, 10, 11])

Set symmetric difference; elments that are in either of the arrays, but not both

In [25]:
np.setxor1d(values, values2)

array([ 3,  5,  8,  9, 10, 11])