Numpy is able to save and load data to and from disk either in text or binary format.
This exercise only discusses numpy's built-in binary format because most users iwll prefer pandas or other tools for loading text or tabular data.

***np.save()*** and ***np.load()*** are the two horkhorse functions for efficinently saving and loading array data on disk.
Arrays are saved by default n an uncompressed raw binary format with file exension ***.npy***.

In [29]:
import numpy as np
arr=np.arange(10)
np.save('some_numpy_array', arr)

In [30]:
np.load('some_numpy_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr2=np.arange(16)

In [32]:
np.savez('array_archive.npz', a=arr, b=arr2) # save multiple arrays in an uncomüpressed archive

In [33]:
arch=np.load('array_archive.npz')
arch

In [34]:
arch['b'] # access indivisual arrays in a npz file

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [35]:
arch['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])