In [13]:
import numpy as np
arr=np.empty((8,4))
arr

array([[8.93080182e-312, 1.06224114e-321, 0.00000000e+000,
        0.00000000e+000],
       [1.89146896e-307, 5.02034658e+175, 1.24689708e-047,
        1.17659820e-047],
       [4.42984146e+175, 3.22115715e-057, 1.50026860e-076,
        6.79355953e-144],
       [3.59751658e+252, 1.46901661e+179, 8.37404147e+242,
        2.59027926e-144],
       [3.80985069e+180, 1.14428494e+243, 2.59027907e-144,
        7.79952704e-143],
       [3.59778970e+179, 9.95131404e-043, 2.64531024e+180,
        9.05977911e-043],
       [2.59027862e-144, 2.59903818e-144, 7.72819857e-091,
        1.90301870e-052],
       [1.25581479e-071, 1.11475752e+261, 1.16318408e-028,
        2.97707521e+296]])

In [14]:
for i in range(8):
    arr[i]=i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

Fancing indexing is a term adopted by NumPy to describe indexing using integer arrays.
To select out a subset of the rows in a particular order, you can simply pass a list of ndarray of integers specifying the desired order

In [15]:
arr[[4,3,2,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [2., 2., 2., 2.],
       [6., 6., 6., 6.]])

In [16]:
arr[[-1,-2,1]]

array([[7., 7., 7., 7.],
       [6., 6., 6., 6.],
       [1., 1., 1., 1.]])

In [20]:
arr2=np.arange(32).reshape(8,4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [21]:
arr2[[1,4,7,2], [0,3,1,2]] # find the element with the following location
# (1,0) (4,3) (7,1) (2,2)

array([ 4, 19, 29, 10])