In [40]:
import numpy as np
arr=np.random.randn(8)
arr

array([-0.16876999, -0.57013443, -0.25228451,  0.99632966, -2.1145807 ,
       -0.89115857,  0.79807122,  1.21843144])

In [41]:
np.abs(arr) # return absolute value

array([0.16876999, 0.57013443, 0.25228451, 0.99632966, 2.1145807 ,
       0.89115857, 0.79807122, 1.21843144])

In [42]:
np.fabs(arr) # return absolute value

array([0.16876999, 0.57013443, 0.25228451, 0.99632966, 2.1145807 ,
       0.89115857, 0.79807122, 1.21843144])

In [43]:
np.square(arr) == arr**2 # np.square() == arr** 2

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [44]:
np.log(arr) # the base is e

C:\Users\fanda\AppData\Local\Temp\ipykernel_22004\3478533125.py:1: RuntimeWarning: invalid value encountered in log
  np.log(arr) # the base is e


array([        nan,         nan,         nan, -0.0036771 ,         nan,
               nan, -0.22555743,  0.19756432])

In [45]:
np.log10(arr) # the base is 10

C:\Users\fanda\AppData\Local\Temp\ipykernel_22004\4072619053.py:1: RuntimeWarning: invalid value encountered in log10
  np.log10(arr) # the base is 10


array([        nan,         nan,         nan, -0.00159694,         nan,
               nan, -0.09795835,  0.0858011 ])

In [46]:
np.log2(arr) # the base is 2

C:\Users\fanda\AppData\Local\Temp\ipykernel_22004\471643831.py:1: RuntimeWarning: invalid value encountered in log2
  np.log2(arr) # the base is 2


array([        nan,         nan,         nan, -0.00530493,         nan,
               nan, -0.32541059,  0.28502507])

In [47]:
np.log1p(arr) # calculate log(1+x)

C:\Users\fanda\AppData\Local\Temp\ipykernel_22004\1776809480.py:1: RuntimeWarning: invalid value encountered in log1p
  np.log1p(arr) # calculate log(1+x)


array([-0.18484873, -0.84428274, -0.29073273,  0.69131032,         nan,
       -2.21786327,  0.58671455,  0.79680039])

In [48]:
# compute sign of eac element
np.sign(arr) # -1(negative), 1(positive), 0(zero)

array([-1., -1., -1.,  1., -1., -1.,  1.,  1.])

In [49]:
np.ceil(arr)

array([-0., -0., -0.,  1., -2., -0.,  1.,  2.])

In [50]:
np.floor(arr)

array([-1., -1., -1.,  0., -3., -1.,  0.,  1.])

In [51]:
# round elements to the nearest integer, perserving the dtype

np.rint(arr)

array([-0., -1., -0.,  1., -2., -1.,  1.,  1.])

In [52]:
np.modf(arr) # return floating part and whole part

(array([-0.16876999, -0.57013443, -0.25228451,  0.99632966, -0.1145807 ,
        -0.89115857,  0.79807122,  0.21843144]),
 array([-0., -0., -0.,  0., -2., -0.,  0.,  1.]))

In [53]:
np.isnan(arr)

array([False, False, False, False, False, False, False, False])

In [54]:
np.isfinite(arr) # return boolean array indicating wheather each element is finite

array([ True,  True,  True,  True,  True,  True,  True,  True])