In [27]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

In [28]:
np.add(arr1,arr2)

array([5, 7, 9])

In [29]:
np.subtract(arr1,arr2)

array([-3, -3, -3])

In [30]:
np.multiply(arr1,arr2)

array([ 4, 10, 18])

In [31]:
np.divide(arr1,arr2)

array([0.25, 0.4 , 0.5 ])

In [32]:
np.floor_divide(arr1, arr2) # truncating the reminder

array([0, 0, 0])

In [33]:
np.power(arr1, arr2)

array([  1,  32, 729])

In [34]:
np.power(arr1,3)

array([ 1,  8, 27], dtype=int32)

In [35]:
np.maximum(arr1,arr2) # element wise-maximum

array([4, 5, 6])

In [36]:
arr3=np.array([np.nan, 6,7]) # element wise-maximum
np.maximum(arr1,arr3)

array([nan,  6.,  7.])

In [37]:
np.fmax(arr1, arr3) # # element wise-maximum, fmax ignores nan

array([1., 6., 7.])

In [38]:
np.minimum(arr1,arr3)# element wise-minimum

array([nan,  2.,  3.])

In [39]:
np.fmin(arr1,arr3)# element wise-minimum, fmin ignores nan

array([1., 2., 3.])

In [40]:
arr1=np.random.randn(8)
arr1

array([-0.33398628, -0.47889584,  0.21813846,  0.67976943, -0.06277242,
        1.9564788 ,  0.20536665,  1.19636527])

In [41]:
arr2=np.random.randn(8)
arr2

array([ 2.19741381,  0.91739933,  0.76977   , -0.09685035,  0.56953011,
        0.83637625,  2.00029378, -1.78441735])

In [42]:
np.mod(arr1,arr2) #element-wise modulus (reminder of division)

array([ 1.86342753,  0.43850349,  0.21813846, -0.09503336,  0.50675769,
        0.28372629,  0.20536665, -0.58805208])

In [43]:
np.copysign(arr1, arr2) # copy sign of of vlaues in second argument to values in first argument

array([ 0.33398628,  0.47889584,  0.21813846, -0.67976943,  0.06277242,
        1.9564788 ,  0.20536665, -1.19636527])

In [44]:
np.greater(arr1, arr2)

array([False, False, False,  True, False,  True, False,  True])

In [45]:
np.greater_equal(arr1,arr2)

array([False, False, False,  True, False,  True, False,  True])

In [46]:
np.less(arr1,arr2)

array([ True,  True,  True, False,  True, False,  True, False])

In [47]:
np.less_equal(arr1,arr2)

array([ True,  True,  True, False,  True, False,  True, False])

In [48]:
np.equal(arr1, arr2)

array([False, False, False, False, False, False, False, False])

In [49]:
np.not_equal(arr1,arr2)

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [50]:
np.logical_and(arr1,arr2)

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [51]:
np.logical_or(arr1,arr2)

array([ True,  True,  True,  True,  True,  True,  True,  True])