The ***numpy.where*** function is a vectorized version of the ternary expression x if condition else y. Suppose we had a boolean array and two arrays of values

In [2]:

import numpy as np
x=np.array([1,2,0,4,5])
y=np.array([1,2,1,1,1])
condition=np.array([True, True, False, True, False])
result=np.where(condition, x,y)
result

array([1, 2, 1, 4, 1])

The second and the thrid arguments to np.where do not have to be arrays. One or both of them can be scalars. A typical use of where in data analysis is to produce a new array of vlaues based on another array.

Replace negative values to -1 and positive values to 1

In [4]:
arr=np.random.randn(4,4)
arr

array([[-1.68898551, -2.39194532,  1.01252741, -1.48183044],
       [ 0.30137303, -0.25174339, -1.87272564,  1.20723268],
       [-0.54802661,  1.16753283,  0.94370426,  0.5725562 ],
       [-0.50720035,  0.71925359,  0.5827683 ,  1.47300213]])

In [6]:
np.where(arr>0, 1, -1)

array([[-1, -1,  1, -1],
       [ 1, -1, -1,  1],
       [-1,  1,  1,  1],
       [-1,  1,  1,  1]])

In [7]:
np.where(arr>0, 2, arr)

array([[-1.68898551, -2.39194532,  2.        , -1.48183044],
       [ 2.        , -0.25174339, -1.87272564,  2.        ],
       [-0.54802661,  2.        ,  2.        ,  2.        ],
       [-0.50720035,  2.        ,  2.        ,  2.        ]])

In [8]:
np.where(arr>0, arr, -2)

array([[-2.        , -2.        ,  1.01252741, -2.        ],
       [ 0.30137303, -2.        , -2.        ,  1.20723268],
       [-2.        ,  1.16753283,  0.94370426,  0.5725562 ],
       [-2.        ,  0.71925359,  0.5827683 ,  1.47300213]])