Like Python's built-in type, numpy arrays can be sorted in-place with the sort method

In [25]:
import numpy as np
arr=np.random.randn(6)
arr

array([ 1.17691162, -0.89741298, -1.25972745,  0.13276953, -0.31943033,
       -1.27581774])

In [26]:
arr.sort()

In [27]:
arr

array([-1.27581774, -1.25972745, -0.89741298, -0.31943033,  0.13276953,
        1.17691162])

Sort each one dimentional section of values in a multidimentional array in-place aling an axis by passing the axis number to sort

In [28]:
arr=np.random.randn(5,3)
arr

array([[-2.65516435, -0.56126219,  0.36206254],
       [ 1.06789816,  0.24910494,  0.69148089],
       [-1.23732342,  0.04044367, -2.08512091],
       [-0.20021946, -0.13402615, -0.06557348],
       [ 0.13245302,  0.68625417,  0.7433259 ]])

In [29]:
arr.sort(axis=0)# can also be written as arr.sort(0)
arr

array([[-2.65516435, -0.56126219, -2.08512091],
       [-1.23732342, -0.13402615, -0.06557348],
       [-0.20021946,  0.04044367,  0.36206254],
       [ 0.13245302,  0.24910494,  0.69148089],
       [ 1.06789816,  0.68625417,  0.7433259 ]])

In [30]:
arr.sort(axis=1) # can also be written as arr.sort(1)
arr

array([[-2.65516435, -2.08512091, -0.56126219],
       [-1.23732342, -0.13402615, -0.06557348],
       [-0.20021946,  0.04044367,  0.36206254],
       [ 0.13245302,  0.24910494,  0.69148089],
       [ 0.68625417,  0.7433259 ,  1.06789816]])

In [39]:
arr=np.random.randn(4)
arr

array([-0.53302192,  0.9505377 , -0.23927689,  0.70272513])

In [40]:
arr.sort()
arr

array([-0.53302192, -0.23927689,  0.70272513,  0.9505377 ])

In [41]:
len(arr)

4

In [42]:
arr[int(0.75*len(arr))] # get 75% percentile

0.9505376990120893