x.dot(y) is equivalent to np.dot(x,y)

In [1]:
import numpy as np
x=np.array([[1.,2.,3.], [4.,5.,6.]])
y=np.array([[6.,23.],[-1,7],[8,9]])

In [2]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [3]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [4]:
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

A matrix product between a two-dimentional array and a suitably sized one-dimentional array results in a one-dimentional array

In [5]:
np.dot(x,np.ones(3))

array([ 6., 15.])