The ***numpy.random*** module supplements the built-in python random with functions for efficiently generating whole arrays of sampel values from many kinds of proability distrubutions.
For example: you can get a 4*4 array of samples from the standard normal distribution using **normal**:

In [16]:
import numpy as np
samples=np.random.normal(size=(4,4))
samples

array([[ 0.40545341,  0.28909194,  1.32115819, -1.54690555],
       [-0.20264632, -0.65596934,  0.19342138,  0.55343891],
       [ 1.31815155, -0.46930528,  0.67555409, -1.81702723],
       [-0.18310854,  1.05896919, -0.39784023,  0.33743765]])

In [17]:
samples=np.random.randn(4,4)
samples

array([[ 1.04757857,  1.04593826,  0.86371729, -0.12209157],
       [ 0.12471295, -0.32279481,  0.84167471,  2.39096052],
       [ 0.07619959, -0.56644593,  0.03614194, -2.0749776 ],
       [ 0.2477922 , -0.89715678, -0.13679483,  0.01828919]])

We say that they are pseudorandom numbers because they are generated by an algorithm with deterministic behavior based on the ***seed*** of the random number generator. You can change numpy's random number generation seed using np.random.seed.
- np.random.seed(0) makes the random numbers predictable:
- >>> numpy.random.seed(0) ; numpy.random.rand(4)
- array([ 0.55,  0.72,  0.6 ,  0.54])
- >>> numpy.random.seed(0) ; numpy.random.rand(4)
- array([ 0.55,  0.72,  0.6 ,  0.54])
- If the random seed is not reset, different numbers appear with every invocation:
- >>> numpy.random.rand(4)
- array([ 0.42,  0.65,  0.44,  0.89])
- >>> numpy.random.rand(4)
- array([ 0.96,  0.38,  0.79,  0.53])

In [21]:
np.random.seed(0)
np.random.normal(size=(4,4))

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433]])

In [22]:
np.random.seed(0)
np.random.normal(size=(4,4))

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433]])

#### Other random methods
- np.random.permutation() : return a random permutation of a sequence or return a permuted range

- np.random.shuffle() : Randomly permute a sequence in-place

- np.random.rand(): draw samples from a uniform distribution

- np.random.randint() : Draw random integers from a given loa-to-high range

- np.random.randn() : Draw samples from a normal distribution with mean 0 and standard deviation 1.

- np.random.binomial() : Draw samples from a binomial distribution

- np.random.normal() : Draw samples from a nomal (gaussian) distribution

- np.random.beta() : Draw samples from a beta distribution

- np.random.chisquare() : Draw samples from a chi-square distribution

- np.random.gamma() : Draw samples from a gamma distribution

- np.random.uniform() : Draw samples from a uniform[0, 1) distrubution